### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Nice app! Here is a proposal of translation in French.

### CODE REVIEW

**Comment by wdehoog** [comment]
Thank you very much. Now I have to find out how to use this since I know nothing of this kind of files. Do you?

**Comment by ghost** [comment]
Nothing is required on your side. As long as there is a "po" folder with .po files in it and the right name (for example "fr" for French or "es" for Spanish) in your code, the user will see the app automatically translated according to the language defined in "General Settings" (English by default if no translation exists).

All you have to do is to update the template (.pot file) when you create a new string of text (indicated by i18n.tr() in your code).

**Comment by wdehoog** [comment]
Ok. Thanks again. One more thing. The SDK IDE complained about "charset=CHARSET" in your po file and I have set it to "charset=UTF-8" is that ok or do you want ISO-Latin1 (iso-8859-1)?

**Comment by ghost** [comment]
UTF-8 seems to be OK.

**Pull request merged**
